// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: Rowknife

#include "../ui.h"

void ui_config_screen_init(void)
{
    ui_config = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_config, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_config, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_config, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_configlogo2 = lv_img_create(ui_config);
    lv_img_set_src(ui_configlogo2, &ui_img_whq_png);
    lv_obj_set_width(ui_configlogo2, LV_SIZE_CONTENT);   /// 96
    lv_obj_set_height(ui_configlogo2, LV_SIZE_CONTENT);    /// 28
    lv_obj_set_x(ui_configlogo2, -169);
    lv_obj_set_y(ui_configlogo2, -115);
    lv_obj_set_align(ui_configlogo2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_configlogo2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_configlogo2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button7 = lv_btn_create(ui_config);
    lv_obj_set_width(ui_Button7, 134);
    lv_obj_set_height(ui_Button7, 50);
    lv_obj_set_x(ui_Button7, -156);
    lv_obj_set_y(ui_Button7, 47);
    lv_obj_set_align(ui_Button7, LV_ALIGN_CENTER);

    ui_Label4 = lv_label_create(ui_Button7);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "单轴模式");
    lv_obj_set_style_text_font(ui_Label4, &ui_font_CN20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button4 = lv_btn_create(ui_config);
    lv_obj_set_width(ui_Button4, 134);
    lv_obj_set_height(ui_Button4, 50);
    lv_obj_set_x(ui_Button4, 5);
    lv_obj_set_y(ui_Button4, 47);
    lv_obj_set_align(ui_Button4, LV_ALIGN_CENTER);

    ui_Label9 = lv_label_create(ui_Button4);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "双轴模式");
    lv_obj_set_style_text_font(ui_Label9, &ui_font_CN20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button3 = lv_btn_create(ui_config);
    lv_obj_set_width(ui_Button3, 134);
    lv_obj_set_height(ui_Button3, 50);
    lv_obj_set_x(ui_Button3, 161);
    lv_obj_set_y(ui_Button3, 47);
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);

    ui_Label11 = lv_label_create(ui_Button3);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "单放双卷模式");
    lv_obj_set_style_text_font(ui_Label11, &ui_font_CN20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Language = lv_btn_create(ui_config);
    lv_obj_set_width(ui_Language, 96);
    lv_obj_set_height(ui_Language, 33);
    lv_obj_set_x(ui_Language, -36);
    lv_obj_set_y(ui_Language, -113);
    lv_obj_set_align(ui_Language, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Language, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Language, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Language, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Language, lv_color_hex(0xF6F6F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Language, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Language, lv_color_hex(0xF6F6F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Language, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label25 = lv_label_create(ui_Language);
    lv_obj_set_width(ui_Label25, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label25, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label25, 2);
    lv_obj_set_y(ui_Label25, 2);
    lv_obj_set_align(ui_Label25, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label25, "中/En");
    lv_obj_set_style_text_color(ui_Label25, lv_color_hex(0x2A2929), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label25, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label25, &ui_font_CN20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button12 = lv_btn_create(ui_config);
    lv_obj_set_width(ui_Button12, 134);
    lv_obj_set_height(ui_Button12, 50);
    lv_obj_set_x(ui_Button12, 9);
    lv_obj_set_y(ui_Button12, -37);
    lv_obj_set_align(ui_Button12, LV_ALIGN_CENTER);

    ui_Label13 = lv_label_create(ui_Button12);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "下编码ID配置");
    lv_obj_set_style_text_font(ui_Label13, &ui_font_CN20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button17 = lv_btn_create(ui_config);
    lv_obj_set_width(ui_Button17, 134);
    lv_obj_set_height(ui_Button17, 50);
    lv_obj_set_x(ui_Button17, -156);
    lv_obj_set_y(ui_Button17, -37);
    lv_obj_set_align(ui_Button17, LV_ALIGN_CENTER);

    ui_Label12 = lv_label_create(ui_Button17);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "上编码ID配置");
    lv_obj_set_style_text_font(ui_Label12, &ui_font_CN20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tomain6 = lv_imgbtn_create(ui_config);
    lv_imgbtn_set_src(ui_tomain6, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_frame_724a_png, NULL);
    lv_imgbtn_set_src(ui_tomain6, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_frame_724a_png, NULL);
    lv_obj_set_height(ui_tomain6, 44);
    lv_obj_set_width(ui_tomain6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_tomain6, 214);
    lv_obj_set_y(ui_tomain6, -110);
    lv_obj_set_align(ui_tomain6, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_tomain6, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_tomain6, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Panel1 = lv_obj_create(ui_config);
    lv_obj_set_width(ui_Panel1, 480);
    lv_obj_set_height(ui_Panel1, 272);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Panel1, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0xC7C1C7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 180, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_UNlock = lv_btn_create(ui_Panel1);
    lv_obj_set_width(ui_UNlock, 113);
    lv_obj_set_height(ui_UNlock, 68);
    lv_obj_set_x(ui_UNlock, 3);
    lv_obj_set_y(ui_UNlock, -69);
    lv_obj_set_align(ui_UNlock, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_UNlock, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_UNlock, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_blend_mode(ui_UNlock, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_UNlock, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 6);
    lv_obj_set_y(ui_Label6, -65);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "解锁");
    lv_obj_set_style_text_font(ui_Label6, &ui_font_CN20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button7, ui_event_Button7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button4, ui_event_Button4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Language, ui_event_Language, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button12, ui_event_Button12, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button17, ui_event_Button17, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_tomain6, ui_event_tomain6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_UNlock, ui_event_UNlock, LV_EVENT_ALL, NULL);

}
