// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: Rowknife

#include "../ui.h"

void ui_MAIN_screen_init(void)
{
    ui_MAIN = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MAIN, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MAIN, lv_color_hex(0xF0F0F0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MAIN, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Labelmode0 = lv_label_create(ui_MAIN);
    lv_obj_set_width(ui_Labelmode0, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labelmode0, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labelmode0, 38);
    lv_obj_set_y(ui_Labelmode0, -117);
    lv_obj_set_align(ui_Labelmode0, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labelmode0, "主动放料系统(双放料模式) ");
    lv_obj_set_style_text_font(ui_Labelmode0, &ui_font_CN20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Labelmode1 = lv_label_create(ui_MAIN);
    lv_obj_set_width(ui_Labelmode1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labelmode1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labelmode1, 38);
    lv_obj_set_y(ui_Labelmode1, -117);
    lv_obj_set_align(ui_Labelmode1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labelmode1, "主动放料系统(单放料模式) ");
    lv_obj_add_flag(ui_Labelmode1, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_font(ui_Labelmode1, &ui_font_CN20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Labelmode2 = lv_label_create(ui_MAIN);
    lv_obj_set_width(ui_Labelmode2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labelmode2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labelmode2, 48);
    lv_obj_set_y(ui_Labelmode2, -117);
    lv_obj_set_align(ui_Labelmode2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labelmode2, "主动放料系统(单放双卷模式) ");
    lv_obj_add_flag(ui_Labelmode2, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_font(ui_Labelmode2, &ui_font_CN20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_upStaTag = lv_label_create(ui_MAIN);
    lv_obj_set_width(ui_upStaTag, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_upStaTag, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_upStaTag, -165);
    lv_obj_set_y(ui_upStaTag, -38);
    lv_obj_set_align(ui_upStaTag, LV_ALIGN_CENTER);
    lv_label_set_text(ui_upStaTag, "电机已释放 ");
    lv_obj_set_style_text_color(ui_upStaTag, lv_color_hex(0x1F8630), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_upStaTag, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_upStaTag, &ui_font_CN20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dwonStaTag = lv_label_create(ui_MAIN);
    lv_obj_set_width(ui_dwonStaTag, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dwonStaTag, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dwonStaTag, -165);
    lv_obj_set_y(ui_dwonStaTag, 53);
    lv_obj_set_align(ui_dwonStaTag, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dwonStaTag, "电机已释放 ");
    lv_obj_set_style_text_color(ui_dwonStaTag, lv_color_hex(0x158630), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_dwonStaTag, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_dwonStaTag, &ui_font_CN20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VERSION = lv_label_create(ui_MAIN);
    lv_obj_set_width(ui_VERSION, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VERSION, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VERSION, 190);
    lv_obj_set_y(ui_VERSION, 119);
    lv_obj_set_align(ui_VERSION, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VERSION, "V.0.0.0.0");
    lv_obj_set_style_text_font(ui_VERSION, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel3 = lv_obj_create(ui_MAIN);
    lv_obj_set_width(ui_Panel3, 294);
    lv_obj_set_height(ui_Panel3, 97);
    lv_obj_set_x(ui_Panel3, 58);
    lv_obj_set_y(ui_Panel3, -50);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Panel3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_STARTup = lv_switch_create(ui_Panel3);
    lv_obj_set_width(ui_STARTup, 187);
    lv_obj_set_height(ui_STARTup, 60);
    lv_obj_set_x(ui_STARTup, -1);
    lv_obj_set_y(ui_STARTup, 10);
    lv_obj_set_align(ui_STARTup, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_STARTup, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_STARTup, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_STARTup, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_STARTup, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED);

    lv_obj_set_style_bg_color(ui_STARTup, lv_color_hex(0xFF0C08), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_STARTup, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    lv_obj_set_style_opa(ui_STARTup, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_textStatUp = lv_label_create(ui_STARTup);
    lv_obj_set_width(ui_textStatUp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_textStatUp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_textStatUp, 2);
    lv_obj_set_y(ui_textStatUp, 0);
    lv_obj_set_align(ui_textStatUp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_textStatUp, "启动上放料 ");
    lv_obj_set_style_text_font(ui_textStatUp, &ui_font_CN20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label28 = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_Label28, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label28, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label28, -105);
    lv_obj_set_y(ui_Label28, -33);
    lv_obj_set_align(ui_Label28, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label28, "上卷料 ");
    lv_obj_set_style_text_color(ui_Label28, lv_color_hex(0xD32C09), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label28, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label28, &ui_font_CN20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_upsta = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_upsta, 138);
    lv_obj_set_height(ui_upsta, 20);
    lv_obj_set_x(ui_upsta, -2);
    lv_obj_set_y(ui_upsta, -33);
    lv_obj_set_align(ui_upsta, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_upsta, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_upsta, "DeviceChecking ");
    lv_obj_set_style_text_font(ui_upsta, &ui_font_CN20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button5 = lv_btn_create(ui_Panel3);
    lv_obj_set_width(ui_Button5, 120);
    lv_obj_set_height(ui_Button5, 60);
    lv_obj_set_x(ui_Button5, 78);
    lv_obj_set_y(ui_Button5, 10);
    lv_obj_set_align(ui_Button5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button5, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button5, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_UpAxisLock = lv_label_create(ui_Button5);
    lv_obj_set_width(ui_UpAxisLock, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_UpAxisLock, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_UpAxisLock, 1);
    lv_obj_set_y(ui_UpAxisLock, 0);
    lv_obj_set_align(ui_UpAxisLock, LV_ALIGN_CENTER);
    lv_label_set_text(ui_UpAxisLock, "电机使能 ");
    lv_obj_set_style_text_color(ui_UpAxisLock, lv_color_hex(0x130303), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_UpAxisLock, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_UpAxisLock, &ui_font_CN20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_MAIN);
    lv_obj_set_width(ui_Panel2, 294);
    lv_obj_set_height(ui_Panel2, 97);
    lv_obj_set_x(ui_Panel2, 58);
    lv_obj_set_y(ui_Panel2, 53);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Panel2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dwonsta = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_dwonsta, 138);
    lv_obj_set_height(ui_dwonsta, 20);
    lv_obj_set_x(ui_dwonsta, -3);
    lv_obj_set_y(ui_dwonsta, -33);
    lv_obj_set_align(ui_dwonsta, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_dwonsta, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_dwonsta, "DeviceChecking ");
    lv_obj_set_style_text_font(ui_dwonsta, &ui_font_CN20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label20 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label20, -105);
    lv_obj_set_y(ui_Label20, -33);
    lv_obj_set_align(ui_Label20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label20, "下卷料 ");
    lv_obj_set_style_text_color(ui_Label20, lv_color_hex(0xD32C09), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label20, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label20, &ui_font_CN20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_STARTdwon = lv_switch_create(ui_Panel2);
    lv_obj_set_width(ui_STARTdwon, 187);
    lv_obj_set_height(ui_STARTdwon, 60);
    lv_obj_set_x(ui_STARTdwon, -1);
    lv_obj_set_y(ui_STARTdwon, 10);
    lv_obj_set_align(ui_STARTdwon, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_STARTdwon, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_STARTdwon, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_STARTdwon, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_STARTdwon, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED);

    lv_obj_set_style_bg_color(ui_STARTdwon, lv_color_hex(0xFF0C08), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_STARTdwon, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    lv_obj_set_style_opa(ui_STARTdwon, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_textStatDwon = lv_label_create(ui_STARTdwon);
    lv_obj_set_width(ui_textStatDwon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_textStatDwon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_textStatDwon, 1);
    lv_obj_set_y(ui_textStatDwon, -1);
    lv_obj_set_align(ui_textStatDwon, LV_ALIGN_CENTER);
    lv_label_set_text(ui_textStatDwon, "启动下放料 ");
    lv_obj_set_style_text_font(ui_textStatDwon, &ui_font_CN20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button10 = lv_btn_create(ui_Panel2);
    lv_obj_set_width(ui_Button10, 120);
    lv_obj_set_height(ui_Button10, 60);
    lv_obj_set_x(ui_Button10, 78);
    lv_obj_set_y(ui_Button10, 10);
    lv_obj_set_align(ui_Button10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button10, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button10, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DownAxisLock = lv_label_create(ui_Button10);
    lv_obj_set_width(ui_DownAxisLock, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DownAxisLock, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DownAxisLock, 2);
    lv_obj_set_y(ui_DownAxisLock, 0);
    lv_obj_set_align(ui_DownAxisLock, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DownAxisLock, "电机使能 ");
    lv_obj_set_style_text_color(ui_DownAxisLock, lv_color_hex(0x010E06), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DownAxisLock, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DownAxisLock, &ui_font_CN20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tomain4 = lv_imgbtn_create(ui_MAIN);
    lv_imgbtn_set_src(ui_tomain4, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_frame_728_png, NULL);
    lv_imgbtn_set_src(ui_tomain4, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_frame_723a_png, NULL);
    lv_obj_set_height(ui_tomain4, 40);
    lv_obj_set_width(ui_tomain4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_tomain4, 216);
    lv_obj_set_y(ui_tomain4, -118);
    lv_obj_set_align(ui_tomain4, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_tomain4, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_tomain4, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_configlogo1 = lv_img_create(ui_MAIN);
    lv_img_set_src(ui_configlogo1, &ui_img_whq_png);
    lv_obj_set_width(ui_configlogo1, LV_SIZE_CONTENT);   /// 96
    lv_obj_set_height(ui_configlogo1, LV_SIZE_CONTENT);    /// 28
    lv_obj_set_x(ui_configlogo1, -170);
    lv_obj_set_y(ui_configlogo1, -116);
    lv_obj_set_align(ui_configlogo1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_configlogo1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_configlogo1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button1 = lv_btn_create(ui_MAIN);
    lv_obj_set_width(ui_Button1, 106);
    lv_obj_set_height(ui_Button1, 38);
    lv_obj_set_x(ui_Button1, -181);
    lv_obj_set_y(ui_Button1, 110);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0xCFC9CF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Button1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_Button1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 1);
    lv_obj_set_y(ui_Label1, 2);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "模式设定");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0x0E0B0C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &ui_font_CN20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label19 = lv_label_create(ui_MAIN);
    lv_obj_set_width(ui_Label19, 64);
    lv_obj_set_height(ui_Label19, 19);
    lv_obj_set_x(ui_Label19, 46);
    lv_obj_set_y(ui_Label19, 118);
    lv_obj_set_align(ui_Label19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label19, "编码器 ");
    lv_obj_set_style_text_font(ui_Label19, &ui_font_CN20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CheckboxC1 = lv_checkbox_create(ui_MAIN);
    lv_checkbox_set_text(ui_CheckboxC1, "");
    lv_obj_set_width(ui_CheckboxC1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CheckboxC1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CheckboxC1, 98);
    lv_obj_set_y(ui_CheckboxC1, 118);
    lv_obj_set_align(ui_CheckboxC1, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_CheckboxC1, LV_STATE_DISABLED);       /// States
    lv_obj_add_flag(ui_CheckboxC1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_CheckboxC2 = lv_checkbox_create(ui_MAIN);
    lv_checkbox_set_text(ui_CheckboxC2, "");
    lv_obj_set_width(ui_CheckboxC2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CheckboxC2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CheckboxC2, 122);
    lv_obj_set_y(ui_CheckboxC2, 118);
    lv_obj_set_align(ui_CheckboxC2, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_CheckboxC2, LV_STATE_DISABLED);       /// States
    lv_obj_add_flag(ui_CheckboxC2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_Label18 = lv_label_create(ui_MAIN);
    lv_obj_set_width(ui_Label18, 40);
    lv_obj_set_height(ui_Label18, 20);
    lv_obj_set_x(ui_Label18, -70);
    lv_obj_set_y(ui_Label18, 118);
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, "电机 ");
    lv_obj_set_style_text_font(ui_Label18, &ui_font_CN20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CheckboxM1 = lv_checkbox_create(ui_MAIN);
    lv_checkbox_set_text(ui_CheckboxM1, "");
    lv_obj_set_width(ui_CheckboxM1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CheckboxM1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CheckboxM1, -28);
    lv_obj_set_y(ui_CheckboxM1, 118);
    lv_obj_set_align(ui_CheckboxM1, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_CheckboxM1, LV_STATE_DISABLED);       /// States
    lv_obj_add_flag(ui_CheckboxM1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_CheckboxM2 = lv_checkbox_create(ui_MAIN);
    lv_checkbox_set_text(ui_CheckboxM2, "");
    lv_obj_set_width(ui_CheckboxM2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CheckboxM2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CheckboxM2, -2);
    lv_obj_set_y(ui_CheckboxM2, 118);
    lv_obj_set_align(ui_CheckboxM2, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_CheckboxM2, LV_STATE_DISABLED);       /// States
    lv_obj_add_flag(ui_CheckboxM2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    lv_obj_add_event_cb(ui_STARTup, ui_event_STARTup, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button5, ui_event_Button5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_STARTdwon, ui_event_STARTdwon, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button10, ui_event_Button10, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_tomain4, ui_event_tomain4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);

}
