// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: Rowknife

#include "../ui.h"

void ui_mode1_screen_init(void)
{
    ui_mode1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_mode1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_mode1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_mode1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image2 = lv_img_create(ui_mode1);
    lv_img_set_src(ui_Image2, &ui_img_whq_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image2, -169);
    lv_obj_set_y(ui_Image2, -116);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label29 = lv_label_create(ui_mode1);
    lv_obj_set_width(ui_Label29, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label29, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label29, -171);
    lv_obj_set_y(ui_Label29, -27);
    lv_obj_set_align(ui_Label29, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label29, "电机方向");
    lv_obj_set_style_text_font(ui_Label29, &ui_font_CN20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label30 = lv_label_create(ui_mode1);
    lv_obj_set_width(ui_Label30, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label30, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label30, -55);
    lv_obj_set_y(ui_Label30, -73);
    lv_obj_set_align(ui_Label30, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label30, "下放料 ");
    lv_obj_set_style_text_font(ui_Label30, &ui_font_CN20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MODE7 = lv_switch_create(ui_mode1);
    lv_obj_set_width(ui_MODE7, 104);
    lv_obj_set_height(ui_MODE7, 45);
    lv_obj_set_x(ui_MODE7, 145);
    lv_obj_set_y(ui_MODE7, 89);
    lv_obj_set_style_radius(ui_MODE7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MODE7, lv_color_hex(0xD3CECE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MODE7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_MODE7, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_opa(ui_MODE7, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Label32 = lv_label_create(ui_MODE7);
    lv_obj_set_width(ui_Label32, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label32, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label32, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label32, "正向");
    lv_obj_set_style_text_font(ui_Label32, &ui_font_CN14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MODE5 = lv_switch_create(ui_mode1);
    lv_obj_set_width(ui_MODE5, 104);
    lv_obj_set_height(ui_MODE5, 45);
    lv_obj_set_x(ui_MODE5, 320);
    lv_obj_set_y(ui_MODE5, 89);
    lv_obj_set_style_radius(ui_MODE5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MODE5, lv_color_hex(0xD3CECE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MODE5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_MODE5, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_opa(ui_MODE5, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_MODE5);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "正向");
    lv_obj_set_style_text_font(ui_Label3, &ui_font_CN14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_JOGCCWUP = lv_btn_create(ui_mode1);
    lv_obj_set_width(ui_JOGCCWUP, 100);
    lv_obj_set_height(ui_JOGCCWUP, 58);
    lv_obj_set_x(ui_JOGCCWUP, 64);
    lv_obj_set_y(ui_JOGCCWUP, 86);
    lv_obj_set_align(ui_JOGCCWUP, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_JOGCCWUP, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_JOGCCWUP, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label34 = lv_label_create(ui_JOGCCWUP);
    lv_obj_set_width(ui_Label34, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label34, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label34, -1);
    lv_obj_set_y(ui_Label34, 0);
    lv_obj_set_align(ui_Label34, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label34, "点动反转");
    lv_obj_set_style_text_font(ui_Label34, &ui_font_CN20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_JOGCCUP = lv_btn_create(ui_mode1);
    lv_obj_set_width(ui_JOGCCUP, 100);
    lv_obj_set_height(ui_JOGCCUP, 58);
    lv_obj_set_x(ui_JOGCCUP, 182);
    lv_obj_set_y(ui_JOGCCUP, 86);
    lv_obj_set_align(ui_JOGCCUP, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_JOGCCUP, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_JOGCCUP, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label35 = lv_label_create(ui_JOGCCUP);
    lv_obj_set_width(ui_Label35, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label35, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label35, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label35, "点动正转");
    lv_obj_set_style_text_font(ui_Label35, &ui_font_CN20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tomain5 = lv_imgbtn_create(ui_mode1);
    lv_imgbtn_set_src(ui_tomain5, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_frame_724a_png, NULL);
    lv_imgbtn_set_src(ui_tomain5, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_frame_724a_png, NULL);
    lv_obj_set_height(ui_tomain5, 44);
    lv_obj_set_width(ui_tomain5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_tomain5, 213);
    lv_obj_set_y(ui_tomain5, -106);
    lv_obj_set_align(ui_tomain5, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_tomain5, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_tomain5, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_JOGCCWDW = lv_btn_create(ui_mode1);
    lv_obj_set_width(ui_JOGCCWDW, 100);
    lv_obj_set_height(ui_JOGCCWDW, 58);
    lv_obj_set_x(ui_JOGCCWDW, -181);
    lv_obj_set_y(ui_JOGCCWDW, 86);
    lv_obj_set_align(ui_JOGCCWDW, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_JOGCCWDW, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_JOGCCWDW, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label21 = lv_label_create(ui_JOGCCWDW);
    lv_obj_set_width(ui_Label21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label21, "点动反转");
    lv_obj_set_style_text_font(ui_Label21, &ui_font_CN20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_JOGCCDW = lv_btn_create(ui_mode1);
    lv_obj_set_width(ui_JOGCCDW, 100);
    lv_obj_set_height(ui_JOGCCDW, 58);
    lv_obj_set_x(ui_JOGCCDW, -60);
    lv_obj_set_y(ui_JOGCCDW, 86);
    lv_obj_set_align(ui_JOGCCDW, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_JOGCCDW, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_JOGCCDW, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label23 = lv_label_create(ui_JOGCCDW);
    lv_obj_set_width(ui_Label23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label23, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label23, "点动正转");
    lv_obj_set_style_text_font(ui_Label23, &ui_font_CN20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label14 = lv_label_create(ui_mode1);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, 118);
    lv_obj_set_y(ui_Label14, -73);
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "上放料 ");
    lv_obj_set_style_text_font(ui_Label14, &ui_font_CN20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_MODE7, ui_event_MODE7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MODE5, ui_event_MODE5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_JOGCCWUP, ui_event_JOGCCWUP, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_JOGCCUP, ui_event_JOGCCUP, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_tomain5, ui_event_tomain5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_JOGCCWDW, ui_event_JOGCCWDW, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_JOGCCDW, ui_event_JOGCCDW, LV_EVENT_ALL, NULL);

}
