// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: Rowknife

#include "../ui.h"

void ui_set_screen_init(void)
{
    ui_set = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_set, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_set, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_set, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tomain = lv_imgbtn_create(ui_set);
    lv_imgbtn_set_src(ui_tomain, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_frame_724a_png, NULL);
    lv_imgbtn_set_src(ui_tomain, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_frame_724a_png, NULL);
    lv_obj_set_height(ui_tomain, 50);
    lv_obj_set_width(ui_tomain, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_tomain, 217);
    lv_obj_set_y(ui_tomain, -113);
    lv_obj_set_align(ui_tomain, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_tomain, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_bg_color(ui_tomain, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_tomain, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_TTT3 = lv_label_create(ui_set);
    lv_obj_set_width(ui_TTT3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TTT3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TTT3, 79);
    lv_obj_set_y(ui_TTT3, -27);
    lv_obj_set_align(ui_TTT3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TTT3, "0");
    lv_obj_set_style_text_font(ui_TTT3, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Downjogspeed = lv_textarea_create(ui_set);
    lv_obj_set_width(ui_Downjogspeed, 78);
    lv_obj_set_height(ui_Downjogspeed, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_Downjogspeed, -111);
    lv_obj_set_y(ui_Downjogspeed, -47);
    lv_obj_set_align(ui_Downjogspeed, LV_ALIGN_CENTER);
    if("0123456789" == "") lv_textarea_set_accepted_chars(ui_Downjogspeed, NULL);
    else lv_textarea_set_accepted_chars(ui_Downjogspeed, "0123456789");
    lv_textarea_set_max_length(ui_Downjogspeed, 4);
    lv_textarea_set_placeholder_text(ui_Downjogspeed, "0");
    lv_textarea_set_one_line(ui_Downjogspeed, true);
    lv_obj_set_style_text_font(ui_Downjogspeed, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_Label5 = lv_label_create(ui_set);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, -195);
    lv_obj_set_y(ui_Label5, -48);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "执行长度\n\n\n执行速度\n\n\n执行时间");
    lv_obj_set_style_text_font(ui_Label5, &ui_font_CN20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DownTensionpos = lv_textarea_create(ui_set);
    lv_obj_set_width(ui_DownTensionpos, 78);
    lv_obj_set_height(ui_DownTensionpos, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_DownTensionpos, -112);
    lv_obj_set_y(ui_DownTensionpos, -104);
    lv_obj_set_align(ui_DownTensionpos, LV_ALIGN_CENTER);
    if(".0123456789" == "") lv_textarea_set_accepted_chars(ui_DownTensionpos, NULL);
    else lv_textarea_set_accepted_chars(ui_DownTensionpos, ".0123456789");
    lv_textarea_set_max_length(ui_DownTensionpos, 6);
    lv_textarea_set_placeholder_text(ui_DownTensionpos, "0");
    lv_textarea_set_one_line(ui_DownTensionpos, true);
    lv_obj_set_style_text_font(ui_DownTensionpos, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_Button13 = lv_btn_create(ui_set);
    lv_obj_set_width(ui_Button13, 94);
    lv_obj_set_height(ui_Button13, 50);
    lv_obj_set_x(ui_Button13, 176);
    lv_obj_set_y(ui_Button13, -30);
    lv_obj_set_align(ui_Button13, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button13, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_DownAxisLock3 = lv_label_create(ui_Button13);
    lv_obj_set_width(ui_DownAxisLock3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DownAxisLock3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DownAxisLock3, 1);
    lv_obj_set_y(ui_DownAxisLock3, 1);
    lv_obj_set_align(ui_DownAxisLock3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DownAxisLock3, "编码归零");
    lv_obj_set_style_text_font(ui_DownAxisLock3, &ui_font_CN20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_set);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, 15);
    lv_obj_set_y(ui_Label7, -67);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "位置\n\n速度\n\n编码");
    lv_obj_set_style_text_font(ui_Label7, &ui_font_CN20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button2 = lv_btn_create(ui_set);
    lv_obj_set_width(ui_Button2, 89);
    lv_obj_set_height(ui_Button2, 56);
    lv_obj_set_x(ui_Button2, -3);
    lv_obj_set_y(ui_Button2, -96);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_set_style_opa(ui_Button2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_timLab = lv_label_create(ui_set);
    lv_obj_set_width(ui_timLab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_timLab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_timLab, -129);
    lv_obj_set_y(ui_timLab, 12);
    lv_obj_set_align(ui_timLab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_timLab, "0");
    lv_obj_set_style_text_font(ui_timLab, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_upTensionpos = lv_label_create(ui_set);
    lv_obj_set_width(ui_upTensionpos, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_upTensionpos, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_upTensionpos, 78);
    lv_obj_set_y(ui_upTensionpos, -108);
    lv_obj_set_align(ui_upTensionpos, LV_ALIGN_CENTER);
    lv_label_set_text(ui_upTensionpos, "0");
    lv_obj_set_style_text_font(ui_upTensionpos, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_upjogspeed = lv_label_create(ui_set);
    lv_obj_set_width(ui_upjogspeed, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_upjogspeed, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_upjogspeed, 79);
    lv_obj_set_y(ui_upjogspeed, -66);
    lv_obj_set_align(ui_upjogspeed, LV_ALIGN_CENTER);
    lv_label_set_text(ui_upjogspeed, "0");
    lv_obj_set_style_text_font(ui_upjogspeed, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button6 = lv_btn_create(ui_set);
    lv_obj_set_width(ui_Button6, 100);
    lv_obj_set_height(ui_Button6, 68);
    lv_obj_set_x(ui_Button6, 165);
    lv_obj_set_y(ui_Button6, -58);
    lv_obj_set_align(ui_Button6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button6, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button6, lv_color_hex(0xCFC9CF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label15 = lv_label_create(ui_Button6);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label15, -1);
    lv_obj_set_y(ui_Label15, 1);
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "进入升级");
    lv_obj_set_style_text_color(ui_Label15, lv_color_hex(0x0B0202), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label15, &ui_font_CN20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_set);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -52);
    lv_obj_set_y(ui_Label2, -105);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "mm");

    ui_Label8 = lv_label_create(ui_set);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, -52);
    lv_obj_set_y(ui_Label8, -46);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "r/m");

    ui_Label10 = lv_label_create(ui_set);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, -52);
    lv_obj_set_y(ui_Label10, 15);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "ms");

    ui_Button9 = lv_btn_create(ui_set);
    lv_obj_set_width(ui_Button9, 79);
    lv_obj_set_height(ui_Button9, 45);
    lv_obj_set_x(ui_Button9, -45);
    lv_obj_set_y(ui_Button9, 84);
    lv_obj_set_align(ui_Button9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button9, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_Button9, &ui_img_frame_724b_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button14 = lv_btn_create(ui_set);
    lv_obj_set_width(ui_Button14, 78);
    lv_obj_set_height(ui_Button14, 45);
    lv_obj_set_x(ui_Button14, -188);
    lv_obj_set_y(ui_Button14, 84);
    lv_obj_set_align(ui_Button14, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button14, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_Button14, &ui_img_frame_724a_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnStart = lv_btn_create(ui_set);
    lv_obj_set_width(ui_BtnStart, 85);
    lv_obj_set_height(ui_BtnStart, 45);
    lv_obj_set_x(ui_BtnStart, 42);
    lv_obj_set_y(ui_BtnStart, 84);
    lv_obj_set_align(ui_BtnStart, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnStart, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnStart, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label17 = lv_label_create(ui_BtnStart);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "启动");
    lv_obj_set_style_text_color(ui_Label17, lv_color_hex(0x100101), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label17, &ui_font_CN20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnCorrelation = lv_btn_create(ui_set);
    lv_obj_set_width(ui_BtnCorrelation, 89);
    lv_obj_set_height(ui_BtnCorrelation, 45);
    lv_obj_set_x(ui_BtnCorrelation, 163);
    lv_obj_set_y(ui_BtnCorrelation, 83);
    lv_obj_set_align(ui_BtnCorrelation, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnCorrelation, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnCorrelation, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label22 = lv_label_create(ui_BtnCorrelation);
    lv_obj_set_width(ui_Label22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label22, "关联");
    lv_obj_set_style_text_color(ui_Label22, lv_color_hex(0x0A0202), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label22, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label22, &ui_font_CN20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dec = lv_label_create(ui_set);
    lv_obj_set_width(ui_dec, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dec, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dec, 79);
    lv_obj_set_y(ui_dec, 17);
    lv_obj_set_align(ui_dec, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dec, "0");
    lv_obj_set_style_text_font(ui_dec, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label27 = lv_label_create(ui_set);
    lv_obj_set_width(ui_Label27, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label27, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label27, 131);
    lv_obj_set_y(ui_Label27, 18);
    lv_obj_set_align(ui_Label27, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label27, "mm");

    ui_Label24 = lv_label_create(ui_set);
    lv_obj_set_width(ui_Label24, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label24, 15);
    lv_obj_set_y(ui_Label24, 16);
    lv_obj_set_align(ui_Label24, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label24, "距离");
    lv_obj_set_style_text_font(ui_Label24, &ui_font_CN20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Keyboard1 = lv_keyboard_create(ui_set);
    lv_keyboard_set_mode(ui_Keyboard1, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_Keyboard1, 246);
    lv_obj_set_height(ui_Keyboard1, 237);
    lv_obj_set_x(ui_Keyboard1, 101);
    lv_obj_set_y(ui_Keyboard1, 0);
    lv_obj_set_align(ui_Keyboard1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_border_width(ui_Keyboard1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_tomain, ui_event_tomain, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Downjogspeed, ui_event_Downjogspeed, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DownTensionpos, ui_event_DownTensionpos, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button13, ui_event_Button13, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button6, ui_event_Button6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button9, ui_event_Button9, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button14, ui_event_Button14, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnStart, ui_event_BtnStart, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnCorrelation, ui_event_BtnCorrelation, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_Keyboard1, ui_Downjogspeed);
    lv_obj_add_event_cb(ui_Keyboard1, ui_event_Keyboard1, LV_EVENT_ALL, NULL);

}
