// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: ver_knife

#include "../ui.h"

void ui_set_screen_init(void)
{
    ui_set = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_set, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_set, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_set, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_configlogo = lv_img_create(ui_set);
    lv_img_set_src(ui_configlogo, &ui_img_whq_png);
    lv_obj_set_width(ui_configlogo, LV_SIZE_CONTENT);   /// 96
    lv_obj_set_height(ui_configlogo, LV_SIZE_CONTENT);    /// 28
    lv_obj_set_x(ui_configlogo, -171);
    lv_obj_set_y(ui_configlogo, -117);
    lv_obj_set_align(ui_configlogo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_configlogo, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_configlogo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_tomain = lv_imgbtn_create(ui_set);
    lv_imgbtn_set_src(ui_tomain, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_frame_724a_png, NULL);
    lv_imgbtn_set_src(ui_tomain, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_frame_724a_png, NULL);
    lv_obj_set_height(ui_tomain, 50);
    lv_obj_set_width(ui_tomain, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_tomain, 217);
    lv_obj_set_y(ui_tomain, -113);
    lv_obj_set_align(ui_tomain, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_tomain, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_tomain, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label7 = lv_label_create(ui_set);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, 94);
    lv_obj_set_y(ui_Label7, -85);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "上放料 ");
    lv_obj_set_style_text_font(ui_Label7, &ui_font_CN20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_set);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, -88);
    lv_obj_set_y(ui_Label10, -85);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "下放料 ");
    lv_obj_set_style_text_font(ui_Label10, &ui_font_CN20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TTT4 = lv_label_create(ui_set);
    lv_obj_set_width(ui_TTT4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TTT4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TTT4, 290);
    lv_obj_set_y(ui_TTT4, 205);
    lv_label_set_text(ui_TTT4, "0");
    lv_obj_set_style_text_font(ui_TTT4, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TTT3 = lv_label_create(ui_set);
    lv_obj_set_width(ui_TTT3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TTT3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TTT3, 104);
    lv_obj_set_y(ui_TTT3, 205);
    lv_label_set_text(ui_TTT3, "0");
    lv_obj_set_style_text_font(ui_TTT3, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_upjogspeed = lv_textarea_create(ui_set);
    lv_obj_set_width(ui_upjogspeed, 70);
    lv_obj_set_height(ui_upjogspeed, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_upjogspeed, 79);
    lv_obj_set_y(ui_upjogspeed, 24);
    lv_obj_set_align(ui_upjogspeed, LV_ALIGN_CENTER);
    if("0123456789" == "") lv_textarea_set_accepted_chars(ui_upjogspeed, NULL);
    else lv_textarea_set_accepted_chars(ui_upjogspeed, "0123456789");
    lv_textarea_set_max_length(ui_upjogspeed, 4);
    lv_textarea_set_placeholder_text(ui_upjogspeed, "0");
    lv_textarea_set_one_line(ui_upjogspeed, true);



    ui_Downjogspeed = lv_textarea_create(ui_set);
    lv_obj_set_width(ui_Downjogspeed, 70);
    lv_obj_set_height(ui_Downjogspeed, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_Downjogspeed, -105);
    lv_obj_set_y(ui_Downjogspeed, 23);
    lv_obj_set_align(ui_Downjogspeed, LV_ALIGN_CENTER);
    if("0123456789" == "") lv_textarea_set_accepted_chars(ui_Downjogspeed, NULL);
    else lv_textarea_set_accepted_chars(ui_Downjogspeed, "0123456789");
    lv_textarea_set_max_length(ui_Downjogspeed, 4);
    lv_textarea_set_placeholder_text(ui_Downjogspeed, "0");
    lv_textarea_set_one_line(ui_Downjogspeed, true);



    ui_Label5 = lv_label_create(ui_set);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, -188);
    lv_obj_set_y(ui_Label5, 21);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "浮辊位置\n\n\n点动速度\n\n\n编码位置");
    lv_obj_set_style_text_font(ui_Label5, &ui_font_CN20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_upTensionpos = lv_textarea_create(ui_set);
    lv_obj_set_width(ui_upTensionpos, 70);
    lv_obj_set_height(ui_upTensionpos, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_upTensionpos, 80);
    lv_obj_set_y(ui_upTensionpos, -41);
    lv_obj_set_align(ui_upTensionpos, LV_ALIGN_CENTER);
    if("0123456789" == "") lv_textarea_set_accepted_chars(ui_upTensionpos, NULL);
    else lv_textarea_set_accepted_chars(ui_upTensionpos, "0123456789");
    lv_textarea_set_max_length(ui_upTensionpos, 4);
    lv_textarea_set_placeholder_text(ui_upTensionpos, "0");
    lv_textarea_set_one_line(ui_upTensionpos, true);



    ui_DownTensionpos = lv_textarea_create(ui_set);
    lv_obj_set_width(ui_DownTensionpos, 70);
    lv_obj_set_height(ui_DownTensionpos, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_DownTensionpos, -105);
    lv_obj_set_y(ui_DownTensionpos, -41);
    lv_obj_set_align(ui_DownTensionpos, LV_ALIGN_CENTER);
    if("0123456789" == "") lv_textarea_set_accepted_chars(ui_DownTensionpos, NULL);
    else lv_textarea_set_accepted_chars(ui_DownTensionpos, "0123456789");
    lv_textarea_set_max_length(ui_DownTensionpos, 4);
    lv_textarea_set_placeholder_text(ui_DownTensionpos, "0");
    lv_textarea_set_one_line(ui_DownTensionpos, true);



    ui_Button13 = lv_btn_create(ui_set);
    lv_obj_set_width(ui_Button13, 100);
    lv_obj_set_height(ui_Button13, 96);
    lv_obj_set_x(ui_Button13, 176);
    lv_obj_set_y(ui_Button13, -5);
    lv_obj_set_align(ui_Button13, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button13, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_DownAxisLock3 = lv_label_create(ui_Button13);
    lv_obj_set_width(ui_DownAxisLock3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DownAxisLock3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DownAxisLock3, 1);
    lv_obj_set_y(ui_DownAxisLock3, 1);
    lv_obj_set_align(ui_DownAxisLock3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DownAxisLock3, "编码归零");
    lv_obj_set_style_text_font(ui_DownAxisLock3, &ui_font_CN20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button14 = lv_btn_create(ui_set);
    lv_obj_set_width(ui_Button14, 100);
    lv_obj_set_height(ui_Button14, 96);
    lv_obj_set_x(ui_Button14, -12);
    lv_obj_set_y(ui_Button14, -5);
    lv_obj_set_align(ui_Button14, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button14, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_DownAxisLock2 = lv_label_create(ui_Button14);
    lv_obj_set_width(ui_DownAxisLock2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DownAxisLock2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DownAxisLock2, 1);
    lv_obj_set_y(ui_DownAxisLock2, 1);
    lv_obj_set_align(ui_DownAxisLock2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DownAxisLock2, "编码归零");
    lv_obj_set_style_text_font(ui_DownAxisLock2, &ui_font_CN20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Keyboard1 = lv_keyboard_create(ui_set);
    lv_keyboard_set_mode(ui_Keyboard1, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_Keyboard1, 246);
    lv_obj_set_height(ui_Keyboard1, 237);
    lv_obj_set_x(ui_Keyboard1, 101);
    lv_obj_set_y(ui_Keyboard1, 0);
    lv_obj_set_align(ui_Keyboard1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_border_width(ui_Keyboard1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button2 = lv_btn_create(ui_set);
    lv_obj_set_width(ui_Button2, 89);
    lv_obj_set_height(ui_Button2, 56);
    lv_obj_set_x(ui_Button2, -3);
    lv_obj_set_y(ui_Button2, -96);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_set_style_opa(ui_Button2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button6 = lv_btn_create(ui_set);
    lv_obj_set_width(ui_Button6, 115);
    lv_obj_set_height(ui_Button6, 51);
    lv_obj_set_x(ui_Button6, 175);
    lv_obj_set_y(ui_Button6, 102);
    lv_obj_set_align(ui_Button6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button6, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button6, lv_color_hex(0xCFC9CF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label15 = lv_label_create(ui_Button6);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label15, -1);
    lv_obj_set_y(ui_Label15, 1);
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "进入升级");
    lv_obj_set_style_text_color(ui_Label15, lv_color_hex(0x0B0202), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label15, &ui_font_CN20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_tomain, ui_event_tomain, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_upjogspeed, ui_event_upjogspeed, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Downjogspeed, ui_event_Downjogspeed, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_upTensionpos, ui_event_upTensionpos, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DownTensionpos, ui_event_DownTensionpos, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button13, ui_event_Button13, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button14, ui_event_Button14, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_Keyboard1, ui_upTensionpos);
    lv_obj_add_event_cb(ui_Keyboard1, ui_event_Keyboard1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button6, ui_event_Button6, LV_EVENT_ALL, NULL);

}
