// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: ver_knife

#include "../ui.h"


// COMPONENT Label4

lv_obj_t * ui_Label4_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Label4;
    cui_Label4 = lv_label_create(comp_parent);
    lv_obj_set_width(cui_Label4, 50);
    lv_obj_set_height(cui_Label4, 16);
    lv_obj_set_x(cui_Label4, -185);
    lv_obj_set_y(cui_Label4, 25);
    lv_obj_set_align(cui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(cui_Label4, "上");

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_LABEL4_NUM);
    children[UI_COMP_LABEL4_LABEL4] = cui_Label4;
    lv_obj_add_event_cb(cui_Label4, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Label4, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_Label4_create_hook(cui_Label4);
    return cui_Label4;
}

