// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: ver_knife

#include "../ui.h"

void ui_comp_Label4_create_hook(lv_obj_t * comp)
{
}
