// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: ver_knife

#ifndef _UI_COMP_LABEL4_H
#define _UI_COMP_LABEL4_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Label4
#define UI_COMP_LABEL4_LABEL4 0
#define _UI_COMP_LABEL4_NUM 1
lv_obj_t * ui_Label4_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
