// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: ver_knife

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_MAIN
void ui_MAIN_screen_init(void);
lv_obj_t * ui_MAIN;
lv_obj_t * ui_Labelmode0;
lv_obj_t * ui_Labelmode1;
lv_obj_t * ui_Labelmode2;
lv_obj_t * ui_upStaTag;
lv_obj_t * ui_dwonStaTag;
lv_obj_t * ui_VERSION;
lv_obj_t * ui_Panel3;
void ui_event_STARTup(lv_event_t * e);
lv_obj_t * ui_STARTup;
lv_obj_t * ui_textStatUp;
lv_obj_t * ui_Label28;
lv_obj_t * ui_upsta;
void ui_event_Button5(lv_event_t * e);
lv_obj_t * ui_Button5;
lv_obj_t * ui_UpAxisLock;
lv_obj_t * ui_Panel2;
lv_obj_t * ui_dwonsta;
lv_obj_t * ui_Label20;
void ui_event_STARTdwon(lv_event_t * e);
lv_obj_t * ui_STARTdwon;
lv_obj_t * ui_textStatDwon;
void ui_event_Button10(lv_event_t * e);
lv_obj_t * ui_Button10;
lv_obj_t * ui_DownAxisLock;
void ui_event_tomain4(lv_event_t * e);
lv_obj_t * ui_tomain4;
lv_obj_t * ui_configlogo1;
void ui_event_Button1(lv_event_t * e);
lv_obj_t * ui_Button1;
lv_obj_t * ui_Label1;
lv_obj_t * ui_Label19;
lv_obj_t * ui_CheckboxC1;
lv_obj_t * ui_CheckboxC2;
lv_obj_t * ui_Label18;
lv_obj_t * ui_CheckboxM1;
lv_obj_t * ui_CheckboxM2;
// CUSTOM VARIABLES


// SCREEN: ui_config
void ui_config_screen_init(void);
lv_obj_t * ui_config;
lv_obj_t * ui_configlogo2;
void ui_event_Button7(lv_event_t * e);
lv_obj_t * ui_Button7;
lv_obj_t * ui_Label4;
void ui_event_Button4(lv_event_t * e);
lv_obj_t * ui_Button4;
lv_obj_t * ui_Label9;
void ui_event_Button3(lv_event_t * e);
lv_obj_t * ui_Button3;
lv_obj_t * ui_Label11;
void ui_event_Language(lv_event_t * e);
lv_obj_t * ui_Language;
lv_obj_t * ui_Label25;
void ui_event_Button12(lv_event_t * e);
lv_obj_t * ui_Button12;
lv_obj_t * ui_Label13;
void ui_event_Button17(lv_event_t * e);
lv_obj_t * ui_Button17;
lv_obj_t * ui_Label12;
void ui_event_tomain6(lv_event_t * e);
lv_obj_t * ui_tomain6;
lv_obj_t * ui_Panel1;
void ui_event_UNlock(lv_event_t * e);
lv_obj_t * ui_UNlock;
lv_obj_t * ui_Label6;
// CUSTOM VARIABLES


// SCREEN: ui_set
void ui_set_screen_init(void);
lv_obj_t * ui_set;
lv_obj_t * ui_configlogo;
void ui_event_tomain(lv_event_t * e);
lv_obj_t * ui_tomain;
lv_obj_t * ui_Label7;
lv_obj_t * ui_Label10;
lv_obj_t * ui_TTT4;
lv_obj_t * ui_TTT3;
void ui_event_upjogspeed(lv_event_t * e);
lv_obj_t * ui_upjogspeed;
void ui_event_Downjogspeed(lv_event_t * e);
lv_obj_t * ui_Downjogspeed;
lv_obj_t * ui_Label5;
void ui_event_upTensionpos(lv_event_t * e);
lv_obj_t * ui_upTensionpos;
void ui_event_DownTensionpos(lv_event_t * e);
lv_obj_t * ui_DownTensionpos;
void ui_event_Button13(lv_event_t * e);
lv_obj_t * ui_Button13;
lv_obj_t * ui_DownAxisLock3;
void ui_event_Button14(lv_event_t * e);
lv_obj_t * ui_Button14;
lv_obj_t * ui_DownAxisLock2;
void ui_event_Keyboard1(lv_event_t * e);
lv_obj_t * ui_Keyboard1;
void ui_event_Button2(lv_event_t * e);
lv_obj_t * ui_Button2;
void ui_event_Button6(lv_event_t * e);
lv_obj_t * ui_Button6;
lv_obj_t * ui_Label15;
// CUSTOM VARIABLES


// SCREEN: ui_mode1
void ui_mode1_screen_init(void);
lv_obj_t * ui_mode1;
lv_obj_t * ui_Image2;
lv_obj_t * ui_Label29;
lv_obj_t * ui_Label30;
void ui_event_MODE7(lv_event_t * e);
lv_obj_t * ui_MODE7;
lv_obj_t * ui_Label32;
void ui_event_MODE5(lv_event_t * e);
lv_obj_t * ui_MODE5;
lv_obj_t * ui_Label3;
void ui_event_JOGCCWUP(lv_event_t * e);
lv_obj_t * ui_JOGCCWUP;
lv_obj_t * ui_Label34;
void ui_event_JOGCCUP(lv_event_t * e);
lv_obj_t * ui_JOGCCUP;
lv_obj_t * ui_Label35;
void ui_event_tomain5(lv_event_t * e);
lv_obj_t * ui_tomain5;
void ui_event_JOGCCWDW(lv_event_t * e);
lv_obj_t * ui_JOGCCWDW;
lv_obj_t * ui_Label21;
void ui_event_JOGCCDW(lv_event_t * e);
lv_obj_t * ui_JOGCCDW;
lv_obj_t * ui_Label23;
lv_obj_t * ui_Label14;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
const lv_img_dsc_t * ui_imgset_frame_[1] = {&ui_img_frame_728_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_STARTup(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_state_modify(ui_tomain4, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
        _ui_state_modify(ui_Button1, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
        _ui_state_modify(ui_Button5, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_state_modify(ui_tomain4, LV_STATE_DISABLED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_Button1, LV_STATE_DISABLED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_Button5, LV_STATE_DISABLED, _UI_MODIFY_STATE_REMOVE);
    }
    if(event_code == LV_EVENT_CLICKED) {
        GUI_CF_startUp(e);
    }
}

void ui_event_Button5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        GUI_setUp_motorEn(e);
    }
}

void ui_event_STARTdwon(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_state_modify(ui_Button10, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
        _ui_state_modify(ui_tomain4, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
        _ui_state_modify(ui_Button1, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_state_modify(ui_Button10, LV_STATE_DISABLED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_tomain4, LV_STATE_DISABLED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_Button1, LV_STATE_DISABLED, _UI_MODIFY_STATE_REMOVE);
    }
    if(event_code == LV_EVENT_CLICKED) {
        GUI_CF_startDwon(e);
    }
}

void ui_event_Button10(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        GUI_setDown_motorEn(e);
    }
}

void ui_event_tomain4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_set, LV_SCR_LOAD_ANIM_FADE_ON, 10, 200, &ui_set_screen_init);
    }
}

void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_mode1, LV_SCR_LOAD_ANIM_FADE_ON, 10, 300, &ui_mode1_screen_init);
    }
}

void ui_event_Button7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        GUI_SetDevSingAxleMod(e);
    }
}

void ui_event_Button4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        GUI_SetDevdoubleAxisMod(e);
    }
}

void ui_event_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        GUI_SetSinglAxisDoubleVolumeMode(e);
    }
}

void ui_event_Language(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        GUI_Language_mode(e);
    }
}

void ui_event_Button12(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        GUI_DWsetEncodeID(e);
    }
}

void ui_event_Button17(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        GUI_UPsetEncodeID(e);
    }
}

void ui_event_tomain6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_set, LV_SCR_LOAD_ANIM_FADE_ON, 10, 200, &ui_set_screen_init);
    }
}

void ui_event_UNlock(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Panel1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_tomain(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MAIN, LV_SCR_LOAD_ANIM_FADE_ON, 10, 200, &ui_MAIN_screen_init);
    }
}

void ui_event_upjogspeed(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_keyboard_set_target(ui_Keyboard1,  ui_upjogspeed);
        GUI_keyPos(e);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_Downjogspeed(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_keyboard_set_target(ui_Keyboard1,  ui_Downjogspeed);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_upTensionpos(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_keyboard_set_target(ui_Keyboard1,  ui_upTensionpos);
        GUI_keyPos(e);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_DownTensionpos(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_keyboard_set_target(ui_Keyboard1,  ui_DownTensionpos);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_Button13(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        GUI_UP_TensionCalibration(e);
    }
}

void ui_event_Button14(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        GUI_Dwon_TensionCalibration(e);
    }
}

void ui_event_Keyboard1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_READY) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        GUI_CF_set_UpParameter(e);
    }
}

void ui_event_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_LONG_PRESSED) {
        _ui_screen_change(&ui_config, LV_SCR_LOAD_ANIM_FADE_ON, 0, 5000, &ui_config_screen_init);
    }
}

void ui_event_Button6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        GUI_ReSet_boot_updata(e);
    }
}

void ui_event_MODE7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        GUI_CF_setDir_down_mode2(e);
    }
}

void ui_event_MODE5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        GUI_CF_setDir_Up(e);
    }
}

void ui_event_JOGCCWUP(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        GUI_Upmotor_Jog_Cw(e);
    }
    if(event_code == LV_EVENT_RELEASED) {
        GUI_Upmotor_Jog_CwStop(e);
    }
}

void ui_event_JOGCCUP(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        GUI_Upmotor_Jog_CC(e);
    }
    if(event_code == LV_EVENT_RELEASED) {
        GUI_Upmotor_Jog_CCstop(e);
    }
}

void ui_event_tomain5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MAIN, LV_SCR_LOAD_ANIM_FADE_ON, 10, 200, &ui_MAIN_screen_init);
    }
}

void ui_event_JOGCCWDW(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        GUI_Downmotor_Jog_Cw(e);
    }
    if(event_code == LV_EVENT_RELEASED) {
        GUI_Downmotor_Jog_Cwstop(e);
    }
}

void ui_event_JOGCCDW(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        GUI_Downmotor_Jog_CC(e);
    }
    if(event_code == LV_EVENT_RELEASED) {
        GUI_Downmotor_Jog_CCstop(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_MAIN_screen_init();
    ui_config_screen_init();
    ui_set_screen_init();
    ui_mode1_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_MAIN);
}
