// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: ver_knife

#ifndef _VER_KNIFE_UI_H
#define _VER_KNIFE_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"


// SCREEN: ui_MAIN
void ui_MAIN_screen_init(void);
extern lv_obj_t * ui_MAIN;
extern lv_obj_t * ui_Labelmode0;
extern lv_obj_t * ui_Labelmode1;
extern lv_obj_t * ui_Labelmode2;
extern lv_obj_t * ui_upStaTag;
extern lv_obj_t * ui_dwonStaTag;
extern lv_obj_t * ui_VERSION;
extern lv_obj_t * ui_Panel3;
void ui_event_STARTup(lv_event_t * e);
extern lv_obj_t * ui_STARTup;
extern lv_obj_t * ui_textStatUp;
extern lv_obj_t * ui_Label28;
extern lv_obj_t * ui_upsta;
void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_UpAxisLock;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_dwonsta;
extern lv_obj_t * ui_Label20;
void ui_event_STARTdwon(lv_event_t * e);
extern lv_obj_t * ui_STARTdwon;
extern lv_obj_t * ui_textStatDwon;
void ui_event_Button10(lv_event_t * e);
extern lv_obj_t * ui_Button10;
extern lv_obj_t * ui_DownAxisLock;
void ui_event_tomain4(lv_event_t * e);
extern lv_obj_t * ui_tomain4;
extern lv_obj_t * ui_configlogo1;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_CheckboxC1;
extern lv_obj_t * ui_CheckboxC2;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_CheckboxM1;
extern lv_obj_t * ui_CheckboxM2;
// CUSTOM VARIABLES

// SCREEN: ui_config
void ui_config_screen_init(void);
extern lv_obj_t * ui_config;
extern lv_obj_t * ui_configlogo2;
void ui_event_Button7(lv_event_t * e);
extern lv_obj_t * ui_Button7;
extern lv_obj_t * ui_Label4;
void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Label9;
void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Label11;
void ui_event_Language(lv_event_t * e);
extern lv_obj_t * ui_Language;
extern lv_obj_t * ui_Label25;
void ui_event_Button12(lv_event_t * e);
extern lv_obj_t * ui_Button12;
extern lv_obj_t * ui_Label13;
void ui_event_Button17(lv_event_t * e);
extern lv_obj_t * ui_Button17;
extern lv_obj_t * ui_Label12;
void ui_event_tomain6(lv_event_t * e);
extern lv_obj_t * ui_tomain6;
extern lv_obj_t * ui_Panel1;
void ui_event_UNlock(lv_event_t * e);
extern lv_obj_t * ui_UNlock;
extern lv_obj_t * ui_Label6;
// CUSTOM VARIABLES

// SCREEN: ui_set
void ui_set_screen_init(void);
extern lv_obj_t * ui_set;
extern lv_obj_t * ui_configlogo;
void ui_event_tomain(lv_event_t * e);
extern lv_obj_t * ui_tomain;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_TTT4;
extern lv_obj_t * ui_TTT3;
void ui_event_upjogspeed(lv_event_t * e);
extern lv_obj_t * ui_upjogspeed;
void ui_event_Downjogspeed(lv_event_t * e);
extern lv_obj_t * ui_Downjogspeed;
extern lv_obj_t * ui_Label5;
void ui_event_upTensionpos(lv_event_t * e);
extern lv_obj_t * ui_upTensionpos;
void ui_event_DownTensionpos(lv_event_t * e);
extern lv_obj_t * ui_DownTensionpos;
void ui_event_Button13(lv_event_t * e);
extern lv_obj_t * ui_Button13;
extern lv_obj_t * ui_DownAxisLock3;
void ui_event_Button14(lv_event_t * e);
extern lv_obj_t * ui_Button14;
extern lv_obj_t * ui_DownAxisLock2;
void ui_event_Keyboard1(lv_event_t * e);
extern lv_obj_t * ui_Keyboard1;
void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
void ui_event_Button6(lv_event_t * e);
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Label15;
// CUSTOM VARIABLES

// SCREEN: ui_mode1
void ui_mode1_screen_init(void);
extern lv_obj_t * ui_mode1;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Label29;
extern lv_obj_t * ui_Label30;
void ui_event_MODE7(lv_event_t * e);
extern lv_obj_t * ui_MODE7;
extern lv_obj_t * ui_Label32;
void ui_event_MODE5(lv_event_t * e);
extern lv_obj_t * ui_MODE5;
extern lv_obj_t * ui_Label3;
void ui_event_JOGCCWUP(lv_event_t * e);
extern lv_obj_t * ui_JOGCCWUP;
extern lv_obj_t * ui_Label34;
void ui_event_JOGCCUP(lv_event_t * e);
extern lv_obj_t * ui_JOGCCUP;
extern lv_obj_t * ui_Label35;
void ui_event_tomain5(lv_event_t * e);
extern lv_obj_t * ui_tomain5;
void ui_event_JOGCCWDW(lv_event_t * e);
extern lv_obj_t * ui_JOGCCWDW;
extern lv_obj_t * ui_Label21;
void ui_event_JOGCCDW(lv_event_t * e);
extern lv_obj_t * ui_JOGCCDW;
extern lv_obj_t * ui_Label23;
extern lv_obj_t * ui_Label14;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_frame_728_png);    // assets/Frame 728.png
LV_IMG_DECLARE(ui_img_frame_723a_png);    // assets/Frame 723A.png
LV_IMG_DECLARE(ui_img_whq_png);    // assets/whq.png
LV_IMG_DECLARE(ui_img_frame_724a_png);    // assets/Frame 724A.png

// FONTS
LV_FONT_DECLARE(ui_font_CN14);
LV_FONT_DECLARE(ui_font_CN20);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
