// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: ver_knife

#include "ui.h"

void GUI_CF_set_mode1(lv_event_t * e)
{
	// Your code here
}

void GUI_CF_set_mode2(lv_event_t * e)
{
	// Your code here
}

void GUI_CF_start(lv_event_t * e)
{
	// Your code here
}

void GUI_CF_setDir_Up(lv_event_t * e)
{
	// Your code here
}

void GUI_setUp_UpperlimitPos(lv_event_t * e)
{
	// Your code here
}

void GUI_setUp_LowerlimitPos(lv_event_t * e)
{
	// Your code here
}

void GUI_UpMotorSelection(lv_event_t * e)
{
	// Your code here
}

void GUI_Upmotor_Jog_CC(lv_event_t * e)
{
	// Your code here
}

void GUI_Upmotor_Jog_CCstop(lv_event_t * e)
{
	// Your code here
}

void GUI_Upmotor_Jog_Cw(lv_event_t * e)
{
	// Your code here
}

void GUI_Upmotor_Jog_CwStop(lv_event_t * e)
{
	// Your code here
}

void GUI_setUp_motorEn(lv_event_t * e)
{
	// Your code here
}

void GUI_CF_setDir_down(lv_event_t * e)
{
	// Your code here
}

void GUI_setDown_UpperlimitPos(lv_event_t * e)
{
	// Your code here
}

void GUI_setDown_LowerlimitPos(lv_event_t * e)
{
	// Your code here
}

void GUI_DownMotorSelection(lv_event_t * e)
{
	// Your code here
}

void GUI_Downmotor_Jog_CC(lv_event_t * e)
{
	// Your code here
}

void GUI_Downmotor_Jog_CCstop(lv_event_t * e)
{
	// Your code here
}

void GUI_Downmotor_Jog_Cw(lv_event_t * e)
{
	// Your code here
}

void GUI_Downmotor_Jog_Cwstop(lv_event_t * e)
{
	// Your code here
}

void GUI_setDown_motorEn(lv_event_t * e)
{
	// Your code here
}


void GUI_CF_set_UpParameter(lv_event_t * e)
{
	// Your code here
}

void GUI_CF_set_DownParameter(lv_event_t * e)
{
	// Your code here
}

void GUI_UP_TensionCalibration(lv_event_t * e)
{
	// Your code here
}

void GUI_Dwon_TensionCalibration(lv_event_t * e)
{
	// Your code here
}

void GUI_DwonEncoderDirSwitch(lv_event_t * e)
{
	// Your code here
}

void GUI_UpEncoderDirSwitch(lv_event_t * e)
{
	// Your code here
}

void GUI_ReSet_boot_updata(lv_event_t * e)
{
	// Your code here
}

void GUI_Language_mode(lv_event_t * e)
{
	// Your code here
}

void GUI_CF_setDir_down_mode2(lv_event_t * e)
{
	// Your code here
}

void GUI_keyPos(lv_event_t * e)
{
	// Your code here
}

void GUI_SetDevSingAxleMod(lv_event_t * e)
{
	// Your code here
}

void GUI_SetDevdoubleAxisMod(lv_event_t * e)
{
	// Your code here
}

void GUI_SetSinglAxisDoubleVolumeMode(lv_event_t * e)
{
	// Your code here
}

void GUI_DWsetEncodeID(lv_event_t * e)
{
	// Your code here
}

void GUI_UPsetEncodeID(lv_event_t * e)
{
	// Your code here
}



void GUI_CF_startUp(lv_event_t * e)
{
	// Your code here
}

void GUI_CF_startDwon(lv_event_t * e)
{
	// Your code here
}
