// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: Rowknife

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void Pretr_claerEncdeCallback(lv_event_t * e);
void GUI_ReSet_boot_updata(lv_event_t * e);
void Pretr_JogReverseCallback(lv_event_t * e);
void Pretr_JogForwardCallback(lv_event_t * e);
void Pretr_MoveStartCallback(lv_event_t * e);
void Pretr_EncdeCorrelationCallback(lv_event_t * e);
void Pretr_setParameterCallback(lv_event_t * e);
void GUI_CF_startUp(lv_event_t * e);
void GUI_setUp_motorEn(lv_event_t * e);
void GUI_CF_startDwon(lv_event_t * e);
void GUI_setDown_motorEn(lv_event_t * e);
void GUI_SetDevSingAxleMod(lv_event_t * e);
void GUI_SetDevdoubleAxisMod(lv_event_t * e);
void GUI_SetSinglAxisDoubleVolumeMode(lv_event_t * e);
void GUI_Language_mode(lv_event_t * e);
void GUI_DWsetEncodeID(lv_event_t * e);
void GUI_UPsetEncodeID(lv_event_t * e);
void GUI_CF_setDir_down_mode2(lv_event_t * e);
void GUI_CF_setDir_Up(lv_event_t * e);
void GUI_Upmotor_Jog_Cw(lv_event_t * e);
void GUI_Upmotor_Jog_CwStop(lv_event_t * e);
void GUI_Upmotor_Jog_CC(lv_event_t * e);
void GUI_Upmotor_Jog_CCstop(lv_event_t * e);
void GUI_Downmotor_Jog_Cw(lv_event_t * e);
void GUI_Downmotor_Jog_Cwstop(lv_event_t * e);
void GUI_Downmotor_Jog_CC(lv_event_t * e);
void GUI_Downmotor_Jog_CCstop(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
